#ifndef LIFXCONSTANTS_H
#define LIFXCONSTANTS_H

/*
GET_PAN_GATEWAY = 0x02
PAN_GATEWAY = 0x03
GET_LIGHT_STATE = 0x65
SET_LIGHT_COLOR = 0x66
LIGHT_STATUS = 0x6b
GET_POWER_STATE = 0x14
SET_POWER_STATE = 0x15
POWER_STATE = 0x16
GET_TIME = 0x04
SET_TIME = 0x05
TIME_STATE = 0x06
GET_BULB_LABEL = 0x17
SET_BULB_LABEL = 0x18
BULB_LABEL = 0x19
GET_VERSION = 0x20
VERSION_STATE = 0x21
GET_INFO = 0x22
INFO_STATE = 0x23
GET_WIFI_INFO = 0x10
WIFI_INFO = 0x11
SET_DIM_ABSOLUTE = 0x68
SET_DIM_RELATIVE = 0x69
*/
// Gateway
#define LIFX_GET_PAN_GATEWAY    0x02
#define LIFX_PAN_GATEWAY        0x03

// Lights
#define LIFX_GET_LIGHT_STATE    0x65
#define LIFX_SET_LIGHT_COLOR    0x66
#define LIFX_LIGHT_STATUS       0x6b
#define LIFX_GET_POWER_STATE    0x14
#define LIFX_SET_POWER_STATE    0x15
#define LIFX_POWER_STATE        0x16
#define LIFX_GET_TIME           0x04
#define LIFX_SET_TIME           0x05
#define LIFX_TIME_STATE         0x06
#define LIFX_GET_BULB_LABEL     0x17
#define LIFX_SET_BULB_LABEL     0x18
#define LIFX_BULB_LABEL         0x19
#define LIFX_GET_VERSION        0x20
#define LIFX_VERSION_STATE      0x21
#define LIFX_GET_INFO           0x22
#define LIFX_INFO_STATE         0x23
#define LIFX_GET_WIFI_INFO      0x10
#define LIFX_WIFI_INFO          0x11
#define LIFX_SET_DIM_ABSOLUTE   0x68
#define LIFX_SET_DIM_RELATIVE   0x69


#endif // LIFXCONSTANTS_H
